#include "VertexTypes.h"

// POSITION COORDINATE Vertex
const VertexElement CUSTOMVERTEX_POSITION_ELEMENT[] =
{
	{0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION,0},
	D3DDECL_END()
};
VertexDeclaration CUSTOMVERTEX_POSITION_DECLARATION = NULL; // It must be created

// POSITION and TEXTURE COORDINATE Vertex
const VertexElement CUSTOMVERTEX_TEXTURE_ELEMENT[] =
{
	{0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION,0},
	{0, 12, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD,0},
	D3DDECL_END()
};
VertexDeclaration CUSTOMVERTEX_TEXTURE_DECLARATION = NULL; // It must be created

// POSITION, NORMALS and TEXTURE COORDINATE Vertex
const VertexElement CUSTOMVERTEX_NORMAL_TEXTURE_ELEMENT[] =
{
	{0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION,0},
	{0, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL, 0},
	{0, 24, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD,0},
	D3DDECL_END()
};
VertexDeclaration CUSTOMVERTEX_NORMAL_TEXTURE_DECLARATION = NULL; // It must be created

// POSITION, NORMALS, TANGENTS and TEXTURE COORDINATE Vertex
const VertexElement CUSTOMVERTEX_NORMAL_TAN_TEXTURE_ELEMENT[] =
{
	{0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION,0},
	{0, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL, 0},
	{0, 24, D3DDECLTYPE_FLOAT4, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 1},
	{0, 40, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD,0},
	D3DDECL_END()
};
VertexDeclaration CUSTOMVERTEX_NORMAL_TAN_TEXTURE_DECLARATION = NULL; // It must be created

// POSITION and COLOR Vertex
const VertexElement CUSTOMVERTEX_COLOR_ELEMENT[] =
{
	{0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION,0},
	{0, 12, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 0},
	D3DDECL_END()
};
VertexDeclaration CUSTOMVERTEX_COLOR_DECLARATION = NULL; // It must be created

// POSITION and 2 TEXTURE COORDINATES Vertex
const VertexElement CUSTOMVERTEX_TEXTURE_LIGHTMAP_ELEMENT[] =
{
	{0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION,0},
	{0, 12, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD,0},
	{0, 20, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD,1},
	D3DDECL_END()
};
VertexDeclaration CUSTOMVERTEX_TEXTURE_LIGHTMAP_DECLARATION = NULL; // It must be created

// POSITION, NORMALS, TEXTURE COORDINATES, 4 BONE WEIGHTS and 4 BONE INDICES Vertex
const VertexElement CUSTOMVERTEX_CAL3D_NORMAL_TAN_TEXTURE_ELEMENT[] =
{
	{0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION,0},
	{0, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL, 0},
	{0, 24, D3DDECLTYPE_FLOAT4, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD,3},
	{0, 40, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD,0},
	{0, 48, D3DDECLTYPE_FLOAT4, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD,1},
	{0, 64, D3DDECLTYPE_FLOAT4, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD,2},
	D3DDECL_END()
};
VertexDeclaration CUSTOMVERTEX_CAL3D_NORMAL_TAN_TEXTURE_DECLARATION = NULL; // It must be created
